### ISSUE TITLE
Add distribution details to the feature list

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#120]
See #44 for a sketch. Details should include the selected distribution and its parameters.

**Comment by FRosner** [comment]
We should probably rename the `Distribution.getType()` method to something like `Distribution.getName()` and make it return some readable string representation of the distribution name.

Additionally we need a method to return the parameters (e.g. `Distribution.getParameterDescription()`).

Those methods combined we are able to print a nice summary of each distribution.

**Comment by Husterknupp** [comment]
Actually I don't know, whether it's neccessary to create a new method, because the `GaussianDistribution` already has a `toString()` method which nearly does the job for this ticket. The only problem is that the returned string is equivalent to "GaussianDistribution", not simply "Gaussian". It even returns the parameters and their values. So wouldn't it be consequent to force every implementaion of `Distribution` to overwrite `toString()` and print these information,  @FRosner ?

**Comment by FRosner** [comment]
@Husterknupp of course it is not necessary. But as I explained in a different issue before, it is bad practice to use `Object.toString()` for other purposes than debugging as you can't say whether it has been overwritten or not. You can't force an implementation to overwrite `Object.toString()` (or at least not during compile time). That's why you should add a corresponding method to the `Distribution` interface (like we did with the feature values).

You are right that the format of `toString()` already looks quite nice. Why is it a problem that the `TYPE` field is currently _GaussianDistribution_ instead of _Gaussian_? If you don't like it just change it!

**Comment by Husterknupp** [comment]
Parameter description of `CategorialDistribution` needs refactoring.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.3
Revision: 24d321693c901fac7baab3144ce183741f4d402a
Built on: 2013-11-05 20:45:56
