### ISSUE TITLE
Change title of Edit Feature dialog

### ISSUE THREAD

**Issue by Husterknupp** [FRosner/DataGenerator#179]
At the moment the title of the Edit Feature dialog is "Add Feature". @FRosner is it a problem to edit the title of this dialog since it is used for both, adding and editing?
![datagenerator 1](https://f.cloud.github.com/assets/1265382/1580427/f8c823b8-51bd-11e3-9d8d-7b76c378a93d.JPG)

**Comment by FRosner** [comment]
Will fix this.

**Comment by FRosner** [comment]
@Husterknupp the dialog class knows whether it is used for editing a feature definition. Thus it should somehow change it's title when it is used for editing. When it is no longer used for editing the title should be reset. It would be nice if this happened directly and hidden in the dialog class instead of specifying it in the Swing menu.

**Comment by FRosner** [comment]
I guess you forgot to cherry-pick your changes in the v0.4 branch? Please do it because otherwise it will not be fixed in 0.4.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.4
Revision: 9c8016a0f925fb552f7328d419a6467d89e436ba
Built on: 2013-11-26 21:27:51
