### ISSUE TITLE
Introduce limit for the number of instances

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#83]
@FRosner there is a limit to the created instances. Maybe remove the 1. at the end, could cause trouble for the user.
![instances](https://f.cloud.github.com/assets/1318613/1120091/85dbd146-1a91-11e3-9507-43ac1ba9dcad.jpg)

**Comment by Bantolomeus** [comment]
I just opened the document during the writing progress.

**Comment by FRosner** [comment]
@Bantolomeus Don't close the issue without saying how you fixed it. If it won't fix, set the label "won't fix" and explain why.

I guess the problem here is that you wanted to generate 10000000000 instances and the generator hasn't finished, yet. 10000000000 is a huge amount and will take a very long time and a lot of disk space. As there is no progress bar you can't see whether it's finished. But I see another problem here. You seemed to be able to press the generate button twice, though it was still exporting into the same file. I should probably check whether an export is running and  maintain a queue.

**Comment by FRosner** [comment]
@Bantolomeus If you want to take a look at the generation process of such huge files (say v2.csv), you can run `tail -f v2.csv` in the git shell. To close tail, just press CTRL+C.
