### ISSUE TITLE
not the choosen amount of instances and one number at the end

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#84]
@FRosner I dont get the right amount of instances, And at the end stand one number alone, even if I have more then one feature.
![wronginstances](https://f.cloud.github.com/assets/1318613/1120138/72b1ec52-1a93-11e3-9cf6-26d652aa4b9e.JPG)

**Comment by Bantolomeus** [comment]
I just opened the document during the writing progress

**Comment by FRosner** [comment]
@Bantolomeus Why are you creating the same issues twice?

Duplicates #83.

**Comment by Bantolomeus** [comment]
@FRosner Well, I was thinking in one issue we work at the problem that there is one number at the end.
And in the other issue we work at the problem, that there isnt the right amount of instances.

But both errors where my fault, because I opened the document during the generating progress.
Can we prevent the user to open the ducument during the generating progress?

**Comment by FRosner** [comment]
We could. But why would you do this? This is typical for windows programs. It prevents the file system from writing concurrently on the same file, right. But it also prevents the user from looking at the document while generating.

I frequently open my results and leave them open so that the results are updated in my editor when a new file is written. However I created a followup issue for the problem that you can press generate again though it's currently exporting.
