### ISSUE TITLE
Provide different log levels to text area logger

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#99]
Info should be printed black or grey, warnings and errors in some other color (orange or red).

**Comment by FRosner** [comment]
@Husterknupp we cannot change the color of JTextArea content. We should use JTextPane or JEditorPane instead, because they support markup to change the color for example. Could you replace the text area by some component that supports formatted text, adjust the warn and error method of TextAreaLogger and extend the existing GUI test?

**Comment by FRosner** [comment]
I will provide tests for the TextAreaLogManager afterwards (#129). Just implement the functionality and make sure you don't break any existing UI tests. Otherwise fix them.

**Comment by FRosner** [comment]
Ok I already fixed #129. So we have to take care of the `TextAreaLogManagerTest` as well.

**Comment by Husterknupp** [comment]
Made a decision for JEditorPane. It provides colored texts, but no non-textual components as JTextPane does. So JEditorPane has better performance than JTextPane.

**Comment by FRosner** [comment]
Agreed.

**Comment by FRosner** [comment]
We need to set the minimum size accordingly.

**Comment by FRosner** [comment]
Did you run all the tests? I guess this failure here belongs to this ticket.

![Failure1](https://f.cloud.github.com/assets/3427394/1349901/5b0d1004-36fe-11e3-8467-e868a83af98f.PNG)

![Failure2](https://f.cloud.github.com/assets/3427394/1349907/743c6c5a-36fe-11e3-8fb0-6435e05d31c8.PNG)

**Comment by FRosner** [comment]
`mvn clean` solved the problem.

**Comment by Husterknupp** [comment]
The colors of logger warnings are not good readable. Probably the shade of orange must be darker.

**Comment by Bantolomeus** [comment]
During the test I tough the orange text is the new ERROR color.
Maybe the warning color shouldn´t be that agressive.
But it could be just my imagination. Lets talk about it.
my suggestions:
![farben warnung](https://f.cloud.github.com/assets/1318613/1477336/9917d4b4-4659-11e3-947f-b9230c6340d3.JPG)

I know it is hard to find a color.

**Comment by FRosner** [comment]
I believe that a warning should be aggressive as it ought to warn. A hint is something nice. A warning should catch the users attention. However it can be discussed whether the shown "warning" should rather be a normal message. If not I find the color suitable. What do you think @Husterknupp?

**Comment by Husterknupp** [comment]
Yah, it might be hard to differentiate between the meaning of orange and red, because both of them are warning.
But I don't think, the warnings should be a normal message. In [this article](http://www.jankoatwarpspeed.com/css-message-boxes-for-different-message-types/) it's said, that a warning should be thrown when an operation could not be completed in a whole. And the error should prompt every time an operation could not be completet at all (I know, the difference between in a whole and at all might be hard to find). But there is a difference and warnings should be something like orange and errors should be red.
But probably this is the case for bigger systems with a lot more different information to show/to log. I don't see the need for three colors at all. Probably there should only be one color for information and one other color for warnings/errors.

**Comment by FRosner** [comment]
I believe your definition fits well on what we did here. We will keep it that way for now.
